import { useState, useEffect, useCallback } from 'react';
import Header from './components/Header';
import PriceSettingsPanel from './components/PriceSettingsPanel';
import ItemTable from './components/ItemTable';
import PrintButton from './components/PrintButton';
import { DEFAULT_PRICES, ITEM_NAMES } from './data/scrapItems';

const STORAGE_KEY = 'scrap_shop_data';

function loadFromStorage() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return null;
    const data = JSON.parse(raw);
    if (data.date) data.date = new Date(data.date);
    return data;
  } catch {
    return null;
  }
}

function createRow(prices) {
  const item = ITEM_NAMES[0];
  return {
    id: crypto.randomUUID(),
    item,
    price: prices[item] ?? 0,
    qty: '',
  };
}

export default function App() {
  const saved = loadFromStorage();

  const [shopName, setShopName] = useState(saved?.shopName ?? 'My Scrap Shop');
  const [date, setDate] = useState(saved?.date ?? new Date());
  const [prices, setPrices] = useState(saved?.prices ?? { ...DEFAULT_PRICES });
  const [rows, setRows] = useState(saved?.rows ?? []);

  // Persist to localStorage on every change
  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, JSON.stringify({ shopName, date, prices, rows }));
  }, [shopName, date, prices, rows]);

  const handlePriceChange = useCallback((item, newPrice) => {
    setPrices(prev => ({ ...prev, [item]: newPrice }));
    // Update all existing rows that use this item
    setRows(prev =>
      prev.map(row => row.item === item ? { ...row, price: newPrice } : row)
    );
  }, []);

  const handleAddRow = useCallback(() => {
    setRows(prev => [...prev, createRow(prices)]);
  }, [prices]);

  const handleUpdateRow = useCallback((id, changes) => {
    setRows(prev =>
      prev.map(row => row.id === id ? { ...row, ...changes } : row)
    );
  }, []);

  const handleDeleteRow = useCallback((id) => {
    setRows(prev => prev.filter(row => row.id !== id));
  }, []);

  const grandTotal = rows.reduce((sum, row) => sum + (row.price || 0) * (row.qty || 0), 0);

  return (
    <div className="min-h-screen bg-gray-100 py-8 px-4 print:bg-white print:p-0 print:py-0">
      <div className="max-w-5xl mx-auto bg-white rounded-2xl shadow-lg p-6 sm:p-8 print-container print:shadow-none print:rounded-none">

        {/* Invoice Header */}
        <div className="text-center mb-2 no-print">
          <span className="text-xs uppercase tracking-widest text-gray-400 font-medium">Scrap Shop Billing System</span>
        </div>

        <Header
          shopName={shopName}
          setShopName={setShopName}
          date={date}
          setDate={setDate}
        />

        {/* Print-only shop name + date */}
        <div className="hidden print:flex justify-between items-start mb-6 pb-4 border-b-2 border-gray-800">
          <div>
            <h1 className="text-2xl font-bold text-gray-800">{shopName}</h1>
            <p className="text-sm text-gray-500 mt-1">Scrap Shop Invoice</p>
          </div>
          <div className="text-right">
            <p className="text-sm text-gray-500">Date</p>
            <p className="font-semibold text-gray-800">
              {date?.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}
            </p>
          </div>
        </div>

        <PriceSettingsPanel prices={prices} onPriceChange={handlePriceChange} />

        <ItemTable
          rows={rows}
          prices={prices}
          date={date}
          onUpdate={handleUpdateRow}
          onDelete={handleDeleteRow}
          onAddRow={handleAddRow}
          grandTotal={grandTotal}
        />

        {/* Footer actions */}
        <div className="mt-6 flex flex-wrap items-center justify-between gap-3 no-print">
          <button
            onClick={() => {
              if (confirm('Clear all rows?')) setRows([]);
            }}
            className="text-sm text-red-400 hover:text-red-600 underline transition"
          >
            Clear All Rows
          </button>
          <PrintButton />
        </div>

        {/* Print footer */}
        <div className="hidden print:block mt-8 pt-4 border-t border-gray-200 text-center text-xs text-gray-400">
          Generated by Scrap Shop Billing System
        </div>
      </div>
    </div>
  );
}
